export function createMaritimeTranscriptAnalysisModel({
  strategyName,
  model,
  hasMaritimeCommandInformation,
  classification,
  recommendedHumanReviewLabel = "",
  vesselInformation,
  commandInformation,
  conversationStructure = null,
  spokenLanguageProportions = null,
  confidence,
  analysisDescription = "",
  analysisRemarks = {},
  transcriptionTiming = null,
  analysisTiming = null,
  debugContext,
  llmResponseText = "",
  rawResponse,
}) {
  return Object.freeze({
    strategyName,
    model,
    hasMaritimeCommandInformation,
    classification,
    recommendedHumanReviewLabel,
    vesselInformation,
    commandInformation,
    conversationStructure,
    spokenLanguageProportions,
    confidence,
    analysisDescription,
    analysisRemarks,
    transcriptionTiming,
    analysisTiming,
    debugContext,
    llmResponseText,
    rawResponse,
  });
}
